/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.vendas;

import controller.ProdutoController;
import view.HomeDashboardView;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Produto;
import model.bean.QuantidadePorVenda;
import model.bean.Venda;
import model.bean.Venda_Produto;
import model.dao.MetodoPagamentoDAO;
import model.dao.ProdutoDAO;
import model.dao.PromoDAO;
import model.dao.UsuarioDAO;
import model.dao.VendaDAO;
import model.dao.Venda_ProdutoDAO;

/**
 *
 * @author h2ose
 */
public class CarrinhoView extends javax.swing.JFrame {
    
    
    private Venda venda = new Venda();
    
    /** Creates new form NovaVendaView
     * @param venda
     * @throws java.sql.SQLException */
    public CarrinhoView(Venda venda) throws SQLException, ParseException {
        initComponents();
        
        ImageIcon logo = new ImageIcon(getClass().getResource("/images/bricks.png"));
        this.setIconImage(logo.getImage());
        this.setTitle("Gerenciador de Estoque");
        
        this.venda = venda;
        this.calculoTotal();
//        totalTxt.setText(String.valueOf(total));
        
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        MetodoPagamentoDAO metodoPagamentoDAO = new MetodoPagamentoDAO();
        PromoDAO promoDAO = new PromoDAO();
        
        vendaIdTxt.setText("  " + String.valueOf(venda.getVenda_id()));
        usuarioTxt.setText("  " + usuarioDAO.getName(venda.getVendedor()) + " " + usuarioDAO.getSurname(venda.getVendedor()));
        metodoPagamentoTxt.setText("  " + metodoPagamentoDAO.getName(venda.getMetodo_pagamento()));
        promoTxt.setText("  " + promoDAO.getName(venda.getPromo()));
        
        SimpleDateFormat dateForm = new SimpleDateFormat("yyyy-MM-dd");
        Date dateFromDb = dateForm.parse(venda.getData());
        SimpleDateFormat dateForm2 = new SimpleDateFormat("dd/MM/yyyy");
        String dateToShow = dateForm2.format(dateFromDb);
        dataTxt.setText("  " + dateToShow);
        
    }
    
    public void calculoTotal() throws SQLException{
        
        double totalParcial = 0.0;
        double desconto = 0.0;
        
        PromoDAO promoDAO = new PromoDAO();
        desconto = promoDAO.getValorDesconto(venda.getPromo());
        
        for(int i = 0; i < carrinhoTable.getRowCount(); i++){
            totalParcial += Double.parseDouble(carrinhoTable.getValueAt(i, 5).toString());
        }
        
        totalParcialTxt.setText(String.format("%,.2f", totalParcial));
        descontoTxt.setText(String.format("%,.2f", totalParcial * desconto));
        totalTxt.setText(String.format("%,.2f", totalParcial - (totalParcial * desconto)));
    }
    
    public void readCarrinhoTable(Produto produto) throws SQLException{
        
        
        
        DefaultTableModel model = (DefaultTableModel) carrinhoTable.getModel();
        
        Object[] produtoCarrinho = {
            produto.getCod_interno(),
            produto.getProduto_id(),
            venda.getVenda_id(),
            produto.getPreco_unitario(),
            (Integer) qtdeNum.getValue(),
            (double) (produto.getPreco_unitario() * (Integer) qtdeNum.getValue())
        };
        
        model.addRow(produtoCarrinho);
        
    }

    private CarrinhoView() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carrinhoTable = new javax.swing.JTable();
        codigoTxt = new javax.swing.JTextField();
        qtdeNum = new javax.swing.JSpinner();
        buttonAdicionar = new javax.swing.JButton();
        buttonRetirar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buttonCancelarVenda = new javax.swing.JButton();
        buttonCompletarVenda = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        totalTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        totalParcialTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        descontoTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        usuarioTxt = new javax.swing.JTextField();
        metodoPagamentoTxt = new javax.swing.JTextField();
        promoTxt = new javax.swing.JTextField();
        dataTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        vendaIdTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("CAIXA");

        carrinhoTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        carrinhoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Produto", "ID Produto", "ID Venda", "Preço", "Qntde", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(carrinhoTable);
        if (carrinhoTable.getColumnModel().getColumnCount() > 0) {
            carrinhoTable.getColumnModel().getColumn(0).setPreferredWidth(200);
            carrinhoTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            carrinhoTable.getColumnModel().getColumn(2).setPreferredWidth(150);
            carrinhoTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            carrinhoTable.getColumnModel().getColumn(4).setPreferredWidth(75);
            carrinhoTable.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        buttonAdicionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/basket_put.png"))); // NOI18N
        buttonAdicionar.setText("Adicionar");
        buttonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarActionPerformed(evt);
            }
        });

        buttonRetirar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonRetirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/basket_remove.png"))); // NOI18N
        buttonRetirar.setText("Retirar");
        buttonRetirar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        buttonRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRetirarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PRODUTOS NO CARRINHO");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Código do Produto:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Quantidade:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(qtdeNum, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(buttonRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qtdeNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(180, 205, 255));

        buttonCancelarVenda.setBackground(new java.awt.Color(255, 87, 0));
        buttonCancelarVenda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonCancelarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart_delete.png"))); // NOI18N
        buttonCancelarVenda.setText("CANCELAR VENDA");
        buttonCancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarVendaActionPerformed(evt);
            }
        });

        buttonCompletarVenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonCompletarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tick.png"))); // NOI18N
        buttonCompletarVenda.setText("COMPLETAR VENDA");
        buttonCompletarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCompletarVendaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/money_dollar.png"))); // NOI18N
        jLabel4.setText("TOTAL:");

        totalTxt.setEditable(false);
        totalTxt.setBackground(new java.awt.Color(200, 200, 200));
        totalTxt.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        totalTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        totalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTxtActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/money_dollar.png"))); // NOI18N
        jLabel11.setText("Total Parcial");

        totalParcialTxt.setEditable(false);
        totalParcialTxt.setBackground(new java.awt.Color(200, 200, 200));
        totalParcialTxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        totalParcialTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalParcialTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        totalParcialTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalParcialTxtActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/money_dollar.png"))); // NOI18N
        jLabel12.setText("Desconto");

        descontoTxt.setEditable(false);
        descontoTxt.setBackground(new java.awt.Color(200, 200, 200));
        descontoTxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        descontoTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        descontoTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        descontoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descontoTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(buttonCancelarVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonCompletarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalParcialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(descontoTxt))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonCancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCompletarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(totalParcialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descontoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1275, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(180, 205, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Vendedor:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Método de Pagamento:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Promoção Aplicada:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Data:");

        usuarioTxt.setEditable(false);
        usuarioTxt.setBackground(new java.awt.Color(200, 200, 200));
        usuarioTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usuarioTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usuarioTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        usuarioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTxtActionPerformed(evt);
            }
        });

        metodoPagamentoTxt.setEditable(false);
        metodoPagamentoTxt.setBackground(new java.awt.Color(200, 200, 200));
        metodoPagamentoTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        metodoPagamentoTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        metodoPagamentoTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        metodoPagamentoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodoPagamentoTxtActionPerformed(evt);
            }
        });

        promoTxt.setEditable(false);
        promoTxt.setBackground(new java.awt.Color(200, 200, 200));
        promoTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        promoTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        promoTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        promoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promoTxtActionPerformed(evt);
            }
        });

        dataTxt.setEditable(false);
        dataTxt.setBackground(new java.awt.Color(200, 200, 200));
        dataTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        dataTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        dataTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dataTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataTxtActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Realizando venda de ID:");

        vendaIdTxt.setEditable(false);
        vendaIdTxt.setBackground(new java.awt.Color(200, 200, 200));
        vendaIdTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        vendaIdTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vendaIdTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vendaIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendaIdTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(usuarioTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(5, 5, 5)
                        .addComponent(metodoPagamentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)
                        .addComponent(promoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(dataTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vendaIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(vendaIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(promoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(metodoPagamentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel7)))))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void totalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTxtActionPerformed

    private void buttonRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRetirarActionPerformed
        
        if(carrinhoTable.getSelectedRow() != -1){
            try {
                ((DefaultTableModel)carrinhoTable.getModel()).removeRow(carrinhoTable.getSelectedRow());
                this.calculoTotal();
            } catch (SQLException ex) {
                Logger.getLogger(CarrinhoView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Por favor selecione uma venda.");
        }
        
    }//GEN-LAST:event_buttonRetirarActionPerformed

    private void buttonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarActionPerformed
        
        try {
            ProdutoDAO produtoDAO = new ProdutoDAO();
            
            if(produtoDAO.authProduto(codigoTxt.getText())){
                if((Integer) qtdeNum.getValue() <= 0){
                    JOptionPane.showMessageDialog(null, "Erro!" + "\n" + "O produto não pode ter quantidade 0 ou menor.");
                }
                else{
                    Produto produto = produtoDAO.getProdutoByCodigoInterno(codigoTxt.getText());
                    this.readCarrinhoTable(produto);
                    codigoTxt.setText("");
                    qtdeNum.setValue(0);
                    this.calculoTotal();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Erro!" + "\n" + "Produto não encontrado.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(CarrinhoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_buttonAdicionarActionPerformed

    private void buttonCancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarVendaActionPerformed
        
        try {
            VendaDAO vendaDAO = new VendaDAO();
            vendaDAO.cancelVenda();
            NovaVendaView novaVendaView = new NovaVendaView();
            novaVendaView.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(NovaVendaView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_buttonCancelarVendaActionPerformed

    private void usuarioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTxtActionPerformed

    private void metodoPagamentoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodoPagamentoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metodoPagamentoTxtActionPerformed

    private void promoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_promoTxtActionPerformed

    private void dataTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataTxtActionPerformed

    private void vendaIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendaIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendaIdTxtActionPerformed

    private void buttonCompletarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCompletarVendaActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) carrinhoTable.getModel();
        System.out.println(carrinhoTable.getRowCount());
        
        if(model.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Adicione algum produto antes de encerrar a venda.");
        }
        else{
            
            int confirm = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja completar a venda?", "Atenção", JOptionPane.YES_NO_OPTION);
            if(confirm == JOptionPane.YES_OPTION){
                
                try {
                    Venda_ProdutoDAO venda_ProdutoDAO = new Venda_ProdutoDAO();

                    for(int i = 0; i < carrinhoTable.getRowCount(); i++){
                        try {
                            Venda_Produto venda_Produto = new Venda_Produto();
                            venda_Produto.setProduto_id((int) carrinhoTable.getValueAt(i, 1));
                            venda_Produto.setVenda_id((int) carrinhoTable.getValueAt(i, 2));
                            venda_Produto.setPreco_unitario((double) carrinhoTable.getValueAt(i, 3));
                            venda_Produto.setQuantidade((int) carrinhoTable.getValueAt(i, 4));
                            venda_Produto.setSubtotal((double) carrinhoTable.getValueAt(i, 5));
                            venda_ProdutoDAO.createVendaProduto(venda_Produto);

                        } catch (SQLException ex) {
                            Logger.getLogger(CarrinhoView.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                    ProdutoController produtoController = new ProdutoController();

                    for(QuantidadePorVenda qpv : produtoController.getQuantidadeItensVenda(venda.getVenda_id())){
                        produtoController.updateQuantidadeProduto(qpv.getQuantidade(), qpv.getProduto_id());
                    }

                    JOptionPane.showMessageDialog(null, "Venda completada com sucesso!");

                    HomeDashboardView homeDashboardView = new HomeDashboardView();
                    homeDashboardView.setVisible(true);
                    this.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(CarrinhoView.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            
            
            
        }
        
    }//GEN-LAST:event_buttonCompletarVendaActionPerformed

    private void totalParcialTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalParcialTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalParcialTxtActionPerformed

    private void descontoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descontoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descontoTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarrinhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarrinhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarrinhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarrinhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarrinhoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionar;
    private javax.swing.JButton buttonCancelarVenda;
    private javax.swing.JButton buttonCompletarVenda;
    private javax.swing.JButton buttonRetirar;
    private javax.swing.JTable carrinhoTable;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JTextField dataTxt;
    private javax.swing.JTextField descontoTxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField metodoPagamentoTxt;
    private javax.swing.JTextField promoTxt;
    private javax.swing.JSpinner qtdeNum;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField totalParcialTxt;
    private javax.swing.JTextField totalTxt;
    private javax.swing.JTextField usuarioTxt;
    private javax.swing.JTextField vendaIdTxt;
    // End of variables declaration//GEN-END:variables

}
